### ISSUE TITLE
Sayma intermittent STPL test failure

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1127]
```
[    15.633640s]  INFO(board_artiq::ad9154): AD9154-1 running STPL test...
[    15.640435s]  INFO(board_artiq::ad9154):   c0 errors: 2
[    15.645347s] ERROR(board_artiq::ad9154): failed to initialize AD9154-1: STPL failed
```

```
[    14.233530s]  INFO(board_artiq::ad9154): AD9154-0 running STPL test...
[    14.240328s]  INFO(board_artiq::ad9154):   c0 errors: 2
[    14.245235s] ERROR(board_artiq::ad9154): failed to initialize AD9154-0: STPL failed
```

```
[    14.233529s]  INFO(board_artiq::ad9154): AD9154-0 running STPL test...
[    14.240329s]  INFO(board_artiq::ad9154):   c0 errors: 0
[    14.245532s]  INFO(board_artiq::ad9154):   c1 errors: 1
[    14.250445s] ERROR(board_artiq::ad9154): failed to initialize AD9154-0: STPL failed
```

**Comment by sbourdeauducq** [comment]
Running this loop never shows a STPL failure if there wasn't one in the first iteration:
```
    loop {
     dac_stpl(dacno, 4, 2)?;
    }
```

Running this, on the other hand, ends with a STPL failure:
```
    loop {
     dac_prbs(dacno)?;
     dac_stpl(dacno, 4, 2)?;
    }
```

So, it seems that something in the PRBS test upsets the DAC or the JESD core.

**Comment by sbourdeauducq** [comment]
@enjoy-digital Have you checked that the JESD core exits PRBS mode cleanly?

**Comment by sbourdeauducq** [comment]
This loop also ends with a STPL failure, so it seems the problem would be in the JESD core and not the DAC:
```
loop {
    dac_prbs(dacno)?;
    dac_reset(dacno);
    dac_cfg_retry(dacno)?;
    dac_stpl(dacno, 4, 2)?;
}
```

**Comment by sbourdeauducq** [comment]
This also causes STPL failure eventually, though it takes a lot of iterations.
```
loop {
    dac_reset(dacno);
    dac_cfg_retry(dacno)?;
    dac_stpl(dacno, 4, 2)?;
}
```
Note: ``dac_cfg_retry`` toggles ``jesd_enable``.

**Comment by enjoy-digital** [comment]
@sbourdeauducq: that's probably better to restart the jesd after a prbs test indeed. (spi reset and jesd core reset as you are doing).

**Comment by sbourdeauducq** [comment]
(Re)starting the JESD still causes some STPL errors as demonstrated here: https://github.com/m-labs/artiq/issues/1127#issuecomment-410962822 so this is not even a workaround.

Why is it "probably better" to "restart" the JESD?

This loop also doesn't cause a STPL error, so it does seem like there are some issues with the "enable" and "prbs" controls of the JESD core:
```
loop {
      dac_reset(dacno);
      dac_setup(dacno, 6_000_000_000)?;
      clock::spin_us(50000);
      dac_stpl(dacno, 4, 2)?;
}
```
(compare with https://github.com/m-labs/artiq/issues/1127#issuecomment-410958501: I essentially stop touching the "enable" control of the JESD core)

**Comment by enjoy-digital** [comment]
I'm not saying it's a workaround. I just don't know how the DAC is exiting the PRBS mode, so don't know is STPL is supposed to work after that.  On the JESD core, exiting the PRBS mode should be clean, since it does not really impact the core itself, we are just injecting prbs datas when PRBS is enabled and then get back to JESD core datas when disabled. I only see this that can impact the JESD core behaviour: https://github.com/m-labs/jesd204b/blob/master/jesd204b/core.py#L87.

Now if can also not be related at all to PRBS, but simply that STPL test fails and means that JESD init is failing. Can you try remosinb PRBS test from the init sequence to see?

**Comment by sbourdeauducq** [comment]
There was no PRBS when I did this: https://github.com/m-labs/artiq/issues/1127#issuecomment-410962822 - and it still caused the STPL problem.

**Comment by enjoy-digital** [comment]
Then this is not related to PRBS. Next step is then to see if when STPL error is reported, DAC is outputing valid data or not.

**Comment by sbourdeauducq** [comment]
It is more frequent after PRBS.

**Comment by enjoy-digital** [comment]
Then regarding https://github.com/m-labs/artiq/issues/1127#issuecomment-410970073, please do STPL test before PRBS (but not logical since we want to check the lower layers first), or add a reset after the PRBS test.

**Comment by sbourdeauducq** [comment]
Again, that won't solve all problems: DAC init + STPL alone already breaks (but more infrequently) - https://github.com/m-labs/artiq/issues/1127#issuecomment-410965924

Also it would be good to understand what is actually going on instead of doing voodoo programming.

**Comment by enjoy-digital** [comment]
Where is is voodoo programming in saying?:
1) Decouple issues by putting PRBS out of the loop.
2) Once done, check that STPL issue is not a false positive by also checking that output is corrupted.

With 2): if output is not corrupted, then this is probably related to the STPL test itself. If also corrupted, then related to the JESD initialization itself.

**Comment by sbourdeauducq** [comment]
This is fine, but I have issues with that:

> please do STPL test before PRBS (but not logical since we want to check the lower layers first), or add a reset after the PRBS test.

> that's probably better to restart the jesd after a prbs test indeed.

**Comment by enjoy-digital** [comment]
I'm saying that i don't know if the DAC can work correctly after a PRBS test without reset, so if you want to avoid a reset, then we need to be sure what can be expected from the DAC. (but from my understanding since the DAC will detect the JESD stream is missing when PRBS is sent, i expect it to require another link establishment to get back to JESD data).

**Comment by sbourdeauducq** [comment]
@enjoy-digital I see no clock domain crossing structure (e.g. ``MultiReg``) between the CSRs ``enable``, ``ready``, ``prbs_config``, and ``stpl_enable`` which are in the ``sys`` domain, and their corresponding signals in ``JESD204BCoreTX`` which are in the ``jesd`` domain. Or am I missing out something?

**Comment by sbourdeauducq** [comment]
Since with the current way the code is organized, the clock domain renaming for ``JESD204BCoreTX`` is outside the core and you do not know what the domain name is in ``JESD204BCoreTXControl``. Is that why you omitted the CDC on those signals?

**Comment by enjoy-digital** [comment]
The way it's coded, JESD204BCoreTX expects these signals in sys clk domain:
-  enable is used by restart (transmitter initialization is managed in sys clk).
- ready is resynchronizer with a Multireg in JESD204BCoreTX.
- prbs_config when used for restart is not resynchronized, but resynchronized when passed to the transmitter.
- stpl_enable is resynchronized with a Multireg in JESD204BCoreTX.

We could maybe resynchronized to sys clk the jsync used in the restart equations, but for the point you are refering, it seems fine.

**Comment by sbourdeauducq** [comment]
> ready is resynchronizer with a Multireg in JESD204BCoreTX.

Resynchronized into the jesd domain, so, that doesn't work.

> prbs_config when used for restart is not resynchronized, but resynchronized when passed to the transmitter.

It is a multi-bit signal. Can it be synchronized with a simple MultiReg?

> We could maybe resynchronized to sys clk the jsync used in the restart equations

"Maybe"? Is it optional?

**Comment by sbourdeauducq** [comment]
> Resynchronized into the jesd domain, so, that doesn't work.

And then it is used for ``restart``, so it can break this signal too.

**Comment by enjoy-digital** [comment]
OK, thanks for the review. (i wouldn't have catched this without a second pair or eyes)
I fixed ready and jsync. BusSynchronizer for prbs_config is not mandatory since temporary mismatch will only cause the wrong prbs to be transmitted for the duration of the mismatch, but if you think it's better, we can change.

**Comment by sbourdeauducq** [comment]
Still present but with lower frequency - saw 2 in 87 reboots.

**Comment by sbourdeauducq** [comment]
Fixed by https://github.com/HarryMakes/artiq/commit/bdf13b555d33ed5cb58e85eb4449cba24bb38bce
Thanks @HarryMakes

**Comment by jbqubit** [comment]
Thanks @HarryMakes!!!!
