### ISSUE TITLE
Document how to get pyserial hwgrep magic strings

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#33]
Put in FAQ:
import serial.tools.list_ports
import pprint
pprint.pprint(serial.tools.list_ports.comports())

**Comment by jordens** [comment]
or just `python3 -m serial.tools.list_ports -v`

**Comment by fallen** [comment]
Done in https://github.com/m-labs/artiq/commit/7821d0f7c8e862eb8999bb3fc299ca21ad59850d

**Comment by sbourdeauducq** [comment]
The purpose of this is to use serial number, not /dev/ttyUSBX nodes.

**Comment by fallen** [comment]
Ack, fixed in https://github.com/m-labs/artiq/commit/f0dddd9f391d1da7b660e85f3ff92d353f532508

**Comment by sbourdeauducq** [comment]
Still not clear and users already know how to list their serial ports (ls /dev, dmesg, windows control panel, etc.). So the FAQ entry should be entitled "...determine the pyserial URL to attach to a device by its serial number".

**Comment by fallen** [comment]
Ah yes you're right, it's not clear : fixed in https://github.com/m-labs/artiq/commit/c38110201942a6ed982c44e5ae3f600b42c64d02
Sorry about that.
