### ISSUE TITLE
Installing board package does not install main artiq package

### ISSUE THREAD

**Issue by KaifengC** [m-labs/artiq#984]
I'm using a window PC and trying to install artiq 4.0.dev from the `dev` channel but seems something goes wrong:
![image](https://user-images.githubusercontent.com/13186802/38971240-d61d52f6-43cc-11e8-8cc0-3295d48ef15e.png)

Then I found I **only** got an `artiq\binaries\kc705-nist_clock` folder installed in this new environment.
I tried to install other versions and found out that this problem first appeared in artiq 3.5.

I guess there's something wrong about the conda setting?

**Comment by whitequark** [comment]
This should have been fixed in 1ef673c2d43c3, but conda is selecting the commit just before that for some reason.

**Comment by sbourdeauducq** [comment]
@KaifengC Do you still have this problem?

**Comment by KaifengC** [comment]
It's still the same. But using `conda install artiq=4.0.dev` in the activated environment makes it work.

**Comment by whitequark** [comment]
Can you `conda update conda` and try again?

**Comment by KaifengC** [comment]
I use `conda update  conda` and update conda to 4.5.4-py36_0. Then I create a new environment, still the same.

```bash
D:\>conda update conda
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment D:\ProgramData\Anaconda3:

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.4.16-0   conda-forge/label/main
    vc:              14-0          conda-forge/label/main

The following packages will be UPDATED:

    conda:           4.3.14-py36_1                        --> 4.5.4-py36_0  con
a-forge/label/main
    openssl:         1.0.2k-vc14_0                        --> 1.0.2o-vc14_0 con
a-forge/label/main [vc14]
    pycosat:         0.6.1-py36_1                         --> 0.6.3-py36_0  con
a-forge/label/main

Proceed ([y]/n)? y

pycosat-0.6.3- 100% |###############################| Time: 0:00:01  60.07 kB/s
conda-4.5.4-py 100% |###############################| Time: 0:00:12  55.41 kB/s

D:\>conda create -n artiq_4-2 artiq-kc705-nist_clock=4.0.dev
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3\envs\artiq_4-2

  added / updated specs:
    - artiq-kc705-nist_clock=4.0.dev


The following NEW packages will be INSTALLED:

    artiq-kc705-nist_clock: 4.0.dev-820+gitbb90fb7d m-labs/label/dev

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > activate artiq_4-2
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


D:\>activate artiq_4-2

(artiq_4-2) D:\>conda list
# packages in environment at D:\ProgramData\Anaconda3\envs\artiq_4-2:
#
# Name                    Version                   Build  Channel
artiq-kc705-nist_clock    4.0.dev         820+gitbb90fb7d    m-labs/label/dev
```

**Comment by sbourdeauducq** [comment]
This is also affecting 3.6.

**Comment by sbourdeauducq** [comment]
Fixed by updating conda-build + https://github.com/m-labs/artiq/commit/d6992f6a0c83f1930197d0ab6fbb3b538bb4d231
